package SimpleContractLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.runtime.ConceptKind;
import jetbrains.mps.smodel.runtime.StaticScope;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActionReference = createDescriptorForActionReference();
  /*package*/ final ConceptDescriptor myConceptActionTrigger = createDescriptorForActionTrigger();
  /*package*/ final ConceptDescriptor myConceptActionTriggerStatement = createDescriptorForActionTriggerStatement();
  /*package*/ final ConceptDescriptor myConceptClause = createDescriptorForClause();
  /*package*/ final ConceptDescriptor myConceptCondition = createDescriptorForCondition();
  /*package*/ final ConceptDescriptor myConceptContract = createDescriptorForContract();
  /*package*/ final ConceptDescriptor myConceptDateTime = createDescriptorForDateTime();
  /*package*/ final ConceptDescriptor myConceptDateTime_Method_isAfter = createDescriptorForDateTime_Method_isAfter();
  /*package*/ final ConceptDescriptor myConceptDateTime_Method_isBefore = createDescriptorForDateTime_Method_isBefore();
  /*package*/ final ConceptDescriptor myConceptDateTime_Reference = createDescriptorForDateTime_Reference();
  /*package*/ final ConceptDescriptor myConceptDateTime_Type = createDescriptorForDateTime_Type();
  /*package*/ final ConceptDescriptor myConceptDuration = createDescriptorForDuration();
  /*package*/ final ConceptDescriptor myConceptDurationType = createDescriptorForDurationType();
  /*package*/ final ConceptDescriptor myConceptDurationWords = createDescriptorForDurationWords();
  /*package*/ final ConceptDescriptor myConceptDuration_Reference = createDescriptorForDuration_Reference();
  /*package*/ final ConceptDescriptor myConceptDuration_Type = createDescriptorForDuration_Type();
  /*package*/ final ConceptDescriptor myConceptElements = createDescriptorForElements();
  /*package*/ final ConceptDescriptor myConceptEmptyContractContent = createDescriptorForEmptyContractContent();
  /*package*/ final ConceptDescriptor myConceptIAction = createDescriptorForIAction();
  /*package*/ final ConceptDescriptor myConceptIClause = createDescriptorForIClause();
  /*package*/ final ConceptDescriptor myConceptIContractContent = createDescriptorForIContractContent();
  /*package*/ final ConceptDescriptor myConceptIElements = createDescriptorForIElements();
  /*package*/ final ConceptDescriptor myConceptIParticipant = createDescriptorForIParticipant();
  /*package*/ final ConceptDescriptor myConceptIVariables = createDescriptorForIVariables();
  /*package*/ final ConceptDescriptor myConceptInteger = createDescriptorForInteger();
  /*package*/ final ConceptDescriptor myConceptInteger_Reference = createDescriptorForInteger_Reference();
  /*package*/ final ConceptDescriptor myConceptModality = createDescriptorForModality();
  /*package*/ final ConceptDescriptor myConceptParticipant = createDescriptorForParticipant();
  /*package*/ final ConceptDescriptor myConceptParticipantReference = createDescriptorForParticipantReference();
  /*package*/ final ConceptDescriptor myConceptParticipant_Method_deposit = createDescriptorForParticipant_Method_deposit();
  /*package*/ final ConceptDescriptor myConceptParticipant_Type = createDescriptorForParticipant_Type();
  /*package*/ final ConceptDescriptor myConceptRequire = createDescriptorForRequire();
  /*package*/ final ConceptDescriptor myConceptTimeSpecification = createDescriptorForTimeSpecification();
  /*package*/ final ConceptDescriptor myConceptTimeTriggerStatement = createDescriptorForTimeTriggerStatement();
  /*package*/ final ConceptDescriptor myConceptTimeTriggerStatement_duration = createDescriptorForTimeTriggerStatement_duration();
  /*package*/ final ConceptDescriptor myConceptTimeTriggerStatement_time = createDescriptorForTimeTriggerStatement_time();
  /*package*/ final ConceptDescriptor myConceptTokenTransaction = createDescriptorForTokenTransaction();
  /*package*/ final ConceptDescriptor myConceptTokenTransaction_Method_amount = createDescriptorForTokenTransaction_Method_amount();
  /*package*/ final ConceptDescriptor myConceptTokenTransaction_Reference = createDescriptorForTokenTransaction_Reference();
  /*package*/ final ConceptDescriptor myConceptTokenTransaction_Type = createDescriptorForTokenTransaction_Type();
  /*package*/ final ConceptDescriptor myConceptTransfer = createDescriptorForTransfer();
  /*package*/ final ConceptDescriptor myConceptTrigger = createDescriptorForTrigger();
  /*package*/ final ConceptDescriptor myConceptTriggerStatement = createDescriptorForTriggerStatement();
  /*package*/ final ConceptDescriptor myConceptaddDuration = createDescriptorForaddDuration();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActionReference, myConceptActionTrigger, myConceptActionTriggerStatement, myConceptClause, myConceptCondition, myConceptContract, myConceptDateTime, myConceptDateTime_Method_isAfter, myConceptDateTime_Method_isBefore, myConceptDateTime_Reference, myConceptDateTime_Type, myConceptDuration, myConceptDurationType, myConceptDurationWords, myConceptDuration_Reference, myConceptDuration_Type, myConceptElements, myConceptEmptyContractContent, myConceptIAction, myConceptIClause, myConceptIContractContent, myConceptIElements, myConceptIParticipant, myConceptIVariables, myConceptInteger, myConceptInteger_Reference, myConceptModality, myConceptParticipant, myConceptParticipantReference, myConceptParticipant_Method_deposit, myConceptParticipant_Type, myConceptRequire, myConceptTimeSpecification, myConceptTimeTriggerStatement, myConceptTimeTriggerStatement_duration, myConceptTimeTriggerStatement_time, myConceptTokenTransaction, myConceptTokenTransaction_Method_amount, myConceptTokenTransaction_Reference, myConceptTokenTransaction_Type, myConceptTransfer, myConceptTrigger, myConceptTriggerStatement, myConceptaddDuration);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.ActionReference:
        return myConceptActionReference;
      case LanguageConceptSwitch.ActionTrigger:
        return myConceptActionTrigger;
      case LanguageConceptSwitch.ActionTriggerStatement:
        return myConceptActionTriggerStatement;
      case LanguageConceptSwitch.Clause:
        return myConceptClause;
      case LanguageConceptSwitch.Condition:
        return myConceptCondition;
      case LanguageConceptSwitch.Contract:
        return myConceptContract;
      case LanguageConceptSwitch.DateTime:
        return myConceptDateTime;
      case LanguageConceptSwitch.DateTime_Method_isAfter:
        return myConceptDateTime_Method_isAfter;
      case LanguageConceptSwitch.DateTime_Method_isBefore:
        return myConceptDateTime_Method_isBefore;
      case LanguageConceptSwitch.DateTime_Reference:
        return myConceptDateTime_Reference;
      case LanguageConceptSwitch.DateTime_Type:
        return myConceptDateTime_Type;
      case LanguageConceptSwitch.Duration:
        return myConceptDuration;
      case LanguageConceptSwitch.DurationType:
        return myConceptDurationType;
      case LanguageConceptSwitch.DurationWords:
        return myConceptDurationWords;
      case LanguageConceptSwitch.Duration_Reference:
        return myConceptDuration_Reference;
      case LanguageConceptSwitch.Duration_Type:
        return myConceptDuration_Type;
      case LanguageConceptSwitch.Elements:
        return myConceptElements;
      case LanguageConceptSwitch.EmptyContractContent:
        return myConceptEmptyContractContent;
      case LanguageConceptSwitch.IAction:
        return myConceptIAction;
      case LanguageConceptSwitch.IClause:
        return myConceptIClause;
      case LanguageConceptSwitch.IContractContent:
        return myConceptIContractContent;
      case LanguageConceptSwitch.IElements:
        return myConceptIElements;
      case LanguageConceptSwitch.IParticipant:
        return myConceptIParticipant;
      case LanguageConceptSwitch.IVariables:
        return myConceptIVariables;
      case LanguageConceptSwitch.Integer:
        return myConceptInteger;
      case LanguageConceptSwitch.Integer_Reference:
        return myConceptInteger_Reference;
      case LanguageConceptSwitch.Modality:
        return myConceptModality;
      case LanguageConceptSwitch.Participant:
        return myConceptParticipant;
      case LanguageConceptSwitch.ParticipantReference:
        return myConceptParticipantReference;
      case LanguageConceptSwitch.Participant_Method_deposit:
        return myConceptParticipant_Method_deposit;
      case LanguageConceptSwitch.Participant_Type:
        return myConceptParticipant_Type;
      case LanguageConceptSwitch.Require:
        return myConceptRequire;
      case LanguageConceptSwitch.TimeSpecification:
        return myConceptTimeSpecification;
      case LanguageConceptSwitch.TimeTriggerStatement:
        return myConceptTimeTriggerStatement;
      case LanguageConceptSwitch.TimeTriggerStatement_duration:
        return myConceptTimeTriggerStatement_duration;
      case LanguageConceptSwitch.TimeTriggerStatement_time:
        return myConceptTimeTriggerStatement_time;
      case LanguageConceptSwitch.TokenTransaction:
        return myConceptTokenTransaction;
      case LanguageConceptSwitch.TokenTransaction_Method_amount:
        return myConceptTokenTransaction_Method_amount;
      case LanguageConceptSwitch.TokenTransaction_Reference:
        return myConceptTokenTransaction_Reference;
      case LanguageConceptSwitch.TokenTransaction_Type:
        return myConceptTokenTransaction_Type;
      case LanguageConceptSwitch.Transfer:
        return myConceptTransfer;
      case LanguageConceptSwitch.Trigger:
        return myConceptTrigger;
      case LanguageConceptSwitch.TriggerStatement:
        return myConceptTriggerStatement;
      case LanguageConceptSwitch.addDuration:
        return myConceptaddDuration;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Action", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff1ff5fdL);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.ConceptFunction
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad8eaeL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4190375612442998269");
    b.version(3);
    b.aggregate("elements", 0x49702a64e18759c0L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L).optional(true).ordered(true).multiple(true).origin("5291776174929172928").done();
    b.kind(ConceptKind.INTERFACE, StaticScope.GLOBAL);
    b.alias("action");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActionReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "ActionReference", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff20a726L);
    b.class_(false, false, false);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4190375612443043622");
    b.version(3);
    b.associate("Action", 0x3a27346aff20a727L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff1ff5fdL).optional(false).origin("4190375612443043623").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActionTrigger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "ActionTrigger", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2e4aefaabc5a3d1L);
    b.class_(false, false, false);
    // extends: SimpleContractLanguage.structure.Trigger
    b.super_(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0deL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/208483874412798929");
    b.version(3);
    b.associate("actionRef", 0x2e4aefaabc5a3d2L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff1ff5fdL).optional(false).origin("208483874412798930").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActionTriggerStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "ActionTriggerStatement", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35ec350cL);
    b.class_(false, false, false);
    // extends: SimpleContractLanguage.structure.TriggerStatement
    b.super_(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0e5L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/1522370374655554828");
    b.version(3);
    b.associate("timeSpecification", 0x15208bca35ec350dL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b979228791b1fL).optional(false).origin("1522370374655554829").done();
    b.associate("participant", 0x15208bca35f3858aL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9886L).optional(false).origin("1522370374656034186").done();
    b.aggregate("triggerRef", 0x15208bca35ec350eL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0deL).optional(false).ordered(true).multiple(false).origin("1522370374655554830").done();
    b.alias("add Action Trigger");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClause() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Clause", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad503a77L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad854dL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/7938852685666597495");
    b.version(3);
    b.associate("participant", 0x6e2c7874ad503a78L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9886L).optional(false).origin("7938852685666597496").done();
    b.associate("modality", 0x2d7b9792287295dbL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b97922866d6c6L).optional(false).origin("3277379807841785307").done();
    b.aggregate("actions", 0x3a27346aff20a72bL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff20a726L).optional(false).ordered(true).multiple(true).origin("4190375612443043627").done();
    b.aggregate("triggerStatement", 0x2e4aefaabc0a0d4L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0e5L).optional(true).ordered(true).multiple(false).origin("208483874412470484").done();
    b.aggregate("condition", 0x3c12506715652a2fL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715652a4dL).optional(true).ordered(true).multiple(false).origin("4328610595527273007").done();
    b.alias("clause");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCondition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Condition", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715652a4dL);
    b.class_(false, false, false);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595527273037");
    b.version(3);
    b.aggregate("Expression", 0x3c12506715652ac6L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("4328610595527273158").done();
    b.alias("add Condition");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContract() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Contract", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/7938852685666555715");
    b.version(3);
    b.aggregate("participants", 0x4b6992bf6a89c522L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad980fL).optional(true).ordered(true).multiple(true).origin("5434035776223036706").done();
    b.aggregate("variables", 0x4b6992bf6a89c526L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6a91a950L).optional(true).ordered(true).multiple(true).origin("5434035776223036710").done();
    b.aggregate("clauses", 0x4b6992bf6a89c529L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad854dL).optional(true).ordered(true).multiple(true).origin("5434035776223036713").done();
    b.aggregate("actions", 0x4b6992bf6a89c52dL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad8eaeL).optional(true).ordered(true).multiple(true).origin("5434035776223036717").done();
    b.alias("contract");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDateTime() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DateTime", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715081694L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6a91a950L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595521173140");
    b.version(3);
    b.alias("DateTime");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDateTime_Method_isAfter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DateTime_Method_isAfter", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c1250671537c673L);
    b.class_(false, false, false);
    b.parent(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46ac030L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595524298355");
    b.version(3);
    b.aggregate("DateTimeArgument", 0x6ab6d4769f14e56bL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("7689567019721876843").done();
    b.alias("isAfter");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDateTime_Method_isBefore() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DateTime_Method_isBefore", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067153a653fL);
    b.class_(false, false, false);
    b.parent(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46ac030L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595524470079");
    b.version(3);
    b.aggregate("DateTimeArgument", 0x6ab6d4769f150c59L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("7689567019721886809").done();
    b.alias("isBefore");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDateTime_Reference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DateTime_Reference", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067151fd807L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595522729991");
    b.version(3);
    b.associate("dateTime", 0x3c125067151fd880L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715081694L).optional(false).origin("4328610595522730112").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDateTime_Type() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DateTime_Type", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067151fd744L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595522729796");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDuration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Duration", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715302e28L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6a91a950L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595523800616");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDurationType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DurationType", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2cf24455866a6cc4L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3238726216150838468");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDurationWords() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "DurationWords", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2cf24455866a62cdL);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3238726216150835917");
    b.version(3);
    b.property("integer", 0x2cf24455866a76bfL).type(PrimitiveTypeId.INTEGER).origin("3238726216150841023").done();
    b.associate("type", 0x2cf24455866a76bdL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2cf24455866a6cc4L).optional(false).origin("3238726216150841021").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDuration_Reference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Duration_Reference", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e19967b5L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174930356149");
    b.version(3);
    b.associate("duration", 0x49702a64e1996816L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715302e28L).optional(false).origin("5291776174930356246").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDuration_Type() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Duration_Type", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e1996b5aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174930357082");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElements() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Elements", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9883L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/7938852685666556035");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmptyContractContent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "EmptyContractContent", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x43d2aa2604af3c2eL);
    b.class_(false, false, false);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad980fL);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6a91a950L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad854dL);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad8eaeL);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4887155625914481710");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "IAction", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad8eaeL);
    b.interface_();
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5434035776225382062");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIClause() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "IClause", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad854dL);
    b.interface_();
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5434035776225379661");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIContractContent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "IContractContent", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.interface_();
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/7938852685666779877");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIElements() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "IElements", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L);
    b.interface_();
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174929172707");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIParticipant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "IParticipant", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad980fL);
    b.interface_();
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5434035776225384463");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIVariables() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "IVariables", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6a91a950L);
    b.interface_();
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5434035776223553872");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Integer", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067153d3804L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad5302e5L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6a91a950L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595524655108");
    b.version(3);
    b.alias("Integer");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInteger_Reference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Integer_Reference", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715400b6eL);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595524840302");
    b.version(3);
    b.associate("Integer", 0x3c12506715400bcfL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067153d3804L).optional(false).origin("4328610595524840399").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModality() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Modality", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b97922866d6c6L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3277379807841015494");
    b.version(3);
    b.alias("modality");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParticipant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Participant", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9886L);
    b.class_(false, false, true);
    // extends: SimpleContractLanguage.structure.Elements
    b.super_(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9883L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x4b6992bf6aad980fL);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/7938852685666556038");
    b.version(3);
    b.alias("Participant");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParticipantReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "ParticipantReference", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2dbbedc3a2b95c56L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3295488976856112214");
    b.version(3);
    b.associate("participant", 0x2dbbedc3a2b95d18L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9886L).optional(false).origin("3295488976856112408").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParticipant_Method_deposit() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Participant_Method_deposit", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x55e1bccfa9c2aceaL);
    b.class_(false, false, false);
    b.parent(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46ac030L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/6188434963076132074");
    b.version(3);
    b.aggregate("IntegerArgument", 0x502961ba254a0f8fL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("5776255449196793743").done();
    b.alias("deposit");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParticipant_Type() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Participant_Type", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x55e1bccfa9c64380L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/6188434963076367232");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRequire() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Require", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x7678ff525f597e98L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/8536853822932876952");
    b.version(3);
    b.aggregate("bool", 0x7678ff525f597ec9L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("8536853822932877001").done();
    b.aggregate("string", 0x7678ff525f597ecbL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L).optional(false).ordered(true).multiple(false).origin("8536853822932877003").done();
    b.alias("ensure");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTimeSpecification() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TimeSpecification", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b979228791b1fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3277379807842212639");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTimeTriggerStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TimeTriggerStatement", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35f748a6L);
    b.class_(false, true, false);
    // extends: SimpleContractLanguage.structure.TriggerStatement
    b.super_(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0e5L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/1522370374656280742");
    b.version(3);
    b.alias("add Time Trigger");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTimeTriggerStatement_duration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TimeTriggerStatement_duration", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067155b545aL);
    b.class_(false, false, false);
    // extends: SimpleContractLanguage.structure.TimeTriggerStatement
    b.super_(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35f748a6L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595526628442");
    b.version(3);
    b.associate("DateTime", 0x3c125067155b54bdL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715081694L).optional(false).origin("4328610595526628541").done();
    b.associate("timeSpecification", 0x3c125067155b55f7L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b979228791b1fL).optional(false).origin("4328610595526628855").done();
    b.aggregate("durationArgument", 0x4b6992bf6a563d9fL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("5434035776219659679").done();
    b.alias("add Duration Trigger");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTimeTriggerStatement_time() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TimeTriggerStatement_time", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c1250671561d371L);
    b.class_(false, false, false);
    // extends: SimpleContractLanguage.structure.TimeTriggerStatement
    b.super_(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35f748a6L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595527054193");
    b.version(3);
    b.associate("timeSpecification", 0x3c1250671561d402L).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b979228791b1fL).optional(false).origin("4328610595527054338").done();
    b.aggregate("DateTimeArgument", 0x3c1250671561d404L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("4328610595527054340").done();
    b.alias("add Time Trigger");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTokenTransaction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TokenTransaction", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18b8ea4L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174929448612");
    b.version(3);
    b.alias("TokenTransaction");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTokenTransaction_Method_amount() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TokenTransaction_Method_amount", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e1a00ee9L);
    b.class_(false, false, false);
    b.parent(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46ac030L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174930792169");
    b.version(3);
    b.alias("amount");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTokenTransaction_Reference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TokenTransaction_Reference", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e196179aL);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174930139034");
    b.version(3);
    b.associate("TokenTransaction", 0x49702a64e19617fbL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18b8ea4L).optional(false).origin("5291776174930139131").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTokenTransaction_Type() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TokenTransaction_Type", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e1994d59L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/5291776174930349401");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransfer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Transfer", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x74e67740044e6ed4L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/8423551269876952788");
    b.version(3);
    b.associate("participant", 0x74e67740044e91deL).target(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9886L).optional(false).origin("8423551269876961758").done();
    b.aggregate("integerArgument", 0x1a4c0201e6fb71bfL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("1894891750409597375").done();
    b.alias("transfer");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrigger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "Trigger", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0deL);
    b.class_(false, true, false);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3277379807842513118");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriggerStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "TriggerStatement", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2d7b9792287db0e5L);
    b.class_(false, true, false);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/3277379807842513125");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForaddDuration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SimpleContractLanguage", "addDuration", 0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067153a67eaL);
    b.class_(false, false, false);
    b.parent(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46ac030L);
    b.origin("r:92ce4a0c-8422-4a51-b26b-04609c64367d(SimpleContractLanguage.structure)/4328610595524470762");
    b.version(3);
    b.aggregate("durationArgument", 0x1a4c0201e712ad81L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("1894891750411120001").done();
    b.alias("addDuration");
    return b.create();
  }
}
