package SimpleContractLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.Arrays;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Transfer_Constraints extends BaseConstraintsDescriptor {
  public Transfer_Constraints() {
    super(CONCEPTS.Transfer$qh);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.participant$k7lb, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:9e415e95-7194-4344-be96-1ba919ec9b6b(SimpleContractLanguage.constraints)", "6625966364249959589");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.Contract$IL, false, false), LINKS.participants$za28), CONCEPTS.Participant$LS)).concat(ListSequence.fromList(Arrays.asList(SNodeOperations.getNode("r:328e4212-b98b-457d-bc1a-e80a188720e5(SimpleContractLanguage.Globals)", "8536853822936700332"), SNodeOperations.getNode("r:328e4212-b98b-457d-bc1a-e80a188720e5(SimpleContractLanguage.Globals)", "1872263145767556595")))));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Transfer$qh = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x74e67740044e6ed4L, "SimpleContractLanguage.structure.Transfer");
    /*package*/ static final SConcept Contract$IL = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L, "SimpleContractLanguage.structure.Contract");
    /*package*/ static final SConcept Participant$LS = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9886L, "SimpleContractLanguage.structure.Participant");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink participant$k7lb = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x74e67740044e6ed4L, 0x74e67740044e91deL, "participant");
    /*package*/ static final SContainmentLink participants$za28 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L, 0x4b6992bf6a89c522L, "participants");
  }
}
