package SimpleContractLanguage.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.ReductionRuleCondition;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.template.ReductionRuleQueryContext;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static boolean rule_Condition_0_0(final BaseMappingRuleContext _context) {
    return !(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.elements$9Xin), CONCEPTS.TokenTransaction$QQ)).isNotEmpty());
  }
  public static boolean rule_Condition_0_1(final BaseMappingRuleContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.elements$9Xin), CONCEPTS.TokenTransaction$QQ)).isNotEmpty();
  }
  public static boolean rule_Condition_0_2(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) == null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) == null) & BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB)).equalsIgnoreCase("Anyone");
  }
  public static boolean rule_Condition_0_3(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) == null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) == null);
  }
  public static boolean rule_Condition_0_4(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) != null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) == null) & BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB)).equalsIgnoreCase("Anyone");
  }
  public static boolean rule_Condition_0_5(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) != null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) == null);
  }
  public static boolean rule_Condition_0_6(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) != null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) != null) & BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB)).equalsIgnoreCase("Anyone");
  }
  public static boolean rule_Condition_0_7(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) != null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) != null);
  }
  public static boolean rule_Condition_0_8(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) == null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) != null) & BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB)).equalsIgnoreCase("Anyone");
  }
  public static boolean rule_Condition_0_9(final BaseMappingRuleContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig) == null) & (SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq) != null);
  }
  public static boolean rule_Condition_0_10(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E), CONCEPTS.Participant_Method_deposit$uS);
  }
  public static boolean rule_Condition_0_11(final BaseMappingRuleContext _context) {
    return !(SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E), CONCEPTS.addDuration$Vc)) & !(SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E), CONCEPTS.DateTime_Method_isAfter$2K));
  }
  public static boolean rule_Condition_0_12(final BaseMappingRuleContext _context) {
    return !(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$JU2H), PROPS.name$MnvL).equalsIgnoreCase("caller"));
  }
  public static boolean rule_Condition_0_13(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$JU2H), PROPS.name$MnvL).equalsIgnoreCase("caller");
  }
  public static boolean rule_Condition_0_14(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E), CONCEPTS.addDuration$Vc);
  }
  public static boolean rule_Condition_0_15(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E), CONCEPTS.DateTime_Method_isAfter$2K);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    if (Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.collectMany(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$zhyC), CONCEPTS.Action$kj)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(it).equalsIgnoreCase("init");
      }
    }), LINKS.elements$9Xin), CONCEPTS.TokenTransaction$QQ)).isNotEmpty()) {
      return "public payable";
    }
    return "public";
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$m9nt)).getElement(0));
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$m9nt)).getElement(0));
  }
  public static Object propertyMacro_GetValue_1_5(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$m9nt)).getElement(0));
  }
  public static Object propertyMacro_GetValue_1_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_2_1(final PropertyMacroContext _context) {
    if (SNodeOperations.hasRole(_context.getNode(), LINKS.elements$9Xin)) {
      return "";
    }
    return ";";
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_1(final PropertyMacroContext _context) {
    if (SNodeOperations.hasRole(_context.getNode(), LINKS.elements$9Xin)) {
      return "";
    }
    return ";";
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_1(final PropertyMacroContext _context) {
    char[] array = SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toCharArray();
    array[0] = Character.toUpperCase(array[0]);
    return new String(array);
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_7_1(final PropertyMacroContext _context) {
    if (SNodeOperations.hasRole(_context.getNode(), LINKS.elements$9Xin)) {
      return "";
    }
    return ";";
  }
  public static Object propertyMacro_GetValue_8_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_8_1(final PropertyMacroContext _context) {
    char[] array = SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toCharArray();
    array[0] = Character.toUpperCase(array[0]);
    return new String(array);
  }
  public static Object propertyMacro_GetValue_9_0(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$IPtB), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return "!";
    }
    return "";
  }
  public static Object propertyMacro_GetValue_9_1(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.triggerRef$IUBX));
  }
  public static Object propertyMacro_GetValue_9_2(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.triggerRef$IUBX));
  }
  public static Object propertyMacro_GetValue_9_3(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$IPtB), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return " already occured.";
    }
    return " did not occur";
  }
  public static Object propertyMacro_GetValue_9_4(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.triggerRef$IUBX));
  }
  public static Object propertyMacro_GetValue_9_5(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$IPtB), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return " != ";
    }
    return " == ";
  }
  public static Object propertyMacro_GetValue_9_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$rnBV), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_9_7(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$rnBV), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_9_8(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$IPtB), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return " did ";
    }
    return " did not ";
  }
  public static Object propertyMacro_GetValue_9_9(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.triggerRef$IUBX));
  }
  public static Object propertyMacro_GetValue_9_10(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.triggerRef$IUBX));
  }
  public static Object propertyMacro_GetValue_9_11(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$IPtB), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return "late";
    }
    return "early";
  }
  public static Object propertyMacro_GetValue_10_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_10_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_11_0(final PropertyMacroContext _context) {
    if (Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.expression$5L7M)), CONCEPTS.Participant_Method_deposit$uS)).isNotEmpty()) {
      return "";
    }
    return ";";
  }
  public static Object propertyMacro_GetValue_12_0(final PropertyMacroContext _context) {
    if (BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.operand$w6IR)).equals("t")) {
      return "msg";
    } else {
      return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.operand$w6IR));
    }
  }
  public static Object propertyMacro_GetValue_12_1(final PropertyMacroContext _context) {
    if (BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E)).equals("amount")) {
      return "value";
    } else {
      return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E));
    }
  }
  public static Object propertyMacro_GetValue_14_0(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), PROPS.value$jgCM));
  }
  public static Object propertyMacro_GetValue_16_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.value$w7MM);
  }
  public static Object propertyMacro_GetValue_18_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.Integer$yKP$), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_19_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$JU2H), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_23_0(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.dateTime$y$gL), PROPS.name$MnvL).equalsIgnoreCase("now")) {
      return "block.timestamp";
    } else if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.dateTime$y$gL), PROPS.name$MnvL).equalsIgnoreCase("contractStart")) {
      return "_contractStart";
    }
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.dateTime$y$gL), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_24_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_24_1(final PropertyMacroContext _context) {
    if (SNodeOperations.hasRole(_context.getNode(), LINKS.elements$9Xin)) {
      return "";
    }
    return ";";
  }
  public static Object propertyMacro_GetValue_27_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$k7lb), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_28_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_28_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_31_0(final PropertyMacroContext _context) {
    return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(_context.getNode(), LINKS.DateTimeArgument$60K2));
  }
  public static Object propertyMacro_GetValue_32_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_32_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.participant$OmiB), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_37_0(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$ruqc), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return "Before(";
    }
    return "After(";
  }
  public static Object propertyMacro_GetValue_37_1(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.DateTime$gLMA), PROPS.name$MnvL).equalsIgnoreCase("contractStart")) {
      return "_contractStart, ";
    }
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.DateTime$gLMA), PROPS.name$MnvL) + ", ";
  }
  public static Object propertyMacro_GetValue_40_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.duration$PA4), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_41_0(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$oYYj), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return "Before(";
    }
    return "After(";
  }
  public static Object propertyMacro_GetValue_41_1(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.timeSpecification$oYYj), PROPS.name$MnvL).equalsIgnoreCase("before")) {
      return "late";
    }
    return "early";
  }
  public static Object propertyMacro_GetValue_42_0(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), PROPS.integer$xlGt));
  }
  public static Object propertyMacro_GetValue_43_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_44_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_45_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_46_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_47_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static SNode sourceNodeQuery_6_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig);
  }
  public static SNode sourceNodeQuery_11_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.expression$5L7M);
  }
  public static SNode sourceNodeQuery_13_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.leftExpression$sEj);
  }
  public static SNode sourceNodeQuery_13_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rightExpression$nvX);
  }
  public static SNode sourceNodeQuery_15_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.bool$pu0);
  }
  public static SNode sourceNodeQuery_15_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.string$pW2);
  }
  public static SNode sourceNodeQuery_17_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.leftExpression$sEj);
  }
  public static SNode sourceNodeQuery_17_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rightExpression$nvX);
  }
  public static SNode sourceNodeQuery_20_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.lValue$splI);
  }
  public static SNode sourceNodeQuery_20_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rValue$spNK);
  }
  public static SNode sourceNodeQuery_25_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.operand$w6IR);
  }
  public static SNode sourceNodeQuery_25_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E);
  }
  public static SNode sourceNodeQuery_26_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.durationArgument$EbIs);
  }
  public static SNode sourceNodeQuery_27_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.integerArgument$9WO6);
  }
  public static SNode sourceNodeQuery_28_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig);
  }
  public static SNode sourceNodeQuery_28_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq);
  }
  public static SNode sourceNodeQuery_29_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.Expression$iyr6);
  }
  public static SNode sourceNodeQuery_30_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.operand$w6IR);
  }
  public static SNode sourceNodeQuery_30_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.operation$gs9E);
  }
  public static SNode sourceNodeQuery_32_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq);
  }
  public static SNode sourceNodeQuery_34_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.leftExpression$sEj);
  }
  public static SNode sourceNodeQuery_34_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rightExpression$nvX);
  }
  public static SNode sourceNodeQuery_35_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.leftExpression$sEj);
  }
  public static SNode sourceNodeQuery_35_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rightExpression$nvX);
  }
  public static SNode sourceNodeQuery_36_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.leftExpression$sEj);
  }
  public static SNode sourceNodeQuery_36_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rightExpression$nvX);
  }
  public static SNode sourceNodeQuery_37_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.durationArgument$1A$c);
  }
  public static SNode sourceNodeQuery_38_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.condition$5R17);
  }
  public static SNode sourceNodeQuery_39_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.leftExpression$sEj);
  }
  public static SNode sourceNodeQuery_39_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.rightExpression$nvX);
  }
  public static SNode sourceNodeQuery_41_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.DateTimeArgument$p4nE);
  }
  public static SNode sourceNodeQuery_42_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.type$xler);
  }
  public static SNode sourceNodeQuery_45_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig);
  }
  public static SNode sourceNodeQuery_46_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.triggerStatement$3Fig);
  }
  public static SNode sourceNodeQuery_46_1(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq);
  }
  public static SNode sourceNodeQuery_47_0(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), LINKS.condition$BBuq);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.participants$za28)).concat(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.variables$zfTx), CONCEPTS.IElements$C3)));
  }
  public static Iterable<SNode> sourceNodesQuery_1_1(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(SLinkOperations.collectMany(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$zhyC), CONCEPTS.Action$kj)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(it).equalsIgnoreCase("init");
      }
    }), LINKS.elements$9Xin)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(SNodeOperations.isInstanceOf(it, CONCEPTS.TokenTransaction$QQ));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_1_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collectMany(SLinkOperations.collect(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$zhyC), CONCEPTS.Action$kj)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(it).equalsIgnoreCase("init");
      }
    }), LINKS.body$e68K), LINKS.statement$53DE);
  }
  public static Iterable<SNode> sourceNodesQuery_1_3(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.actions$zhyC), CONCEPTS.Action$kj)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(it).equalsIgnoreCase("init"));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_1_4(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.clauses$zgA$), CONCEPTS.Clause$Sq);
  }
  public static Iterable<SNode> sourceNodesQuery_1_5(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.clauses$zgA$), CONCEPTS.Clause$Sq);
  }
  public static Iterable<SNode> sourceNodesQuery_4_0(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.elements$9Xin)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(SNodeOperations.isInstanceOf(it, CONCEPTS.TokenTransaction$QQ));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_4_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.body$e68K), LINKS.statement$53DE);
  }
  public static Iterable<SNode> sourceNodesQuery_8_0(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), LINKS.elements$9Xin)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(SNodeOperations.isInstanceOf(it, CONCEPTS.TokenTransaction$QQ));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_8_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.body$e68K), LINKS.statement$53DE);
  }
  public static Iterable<SNode> sourceNodesQuery_38_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getNode(), LINKS.ifTrue$5Rg8), LINKS.statement$53DE);
  }
  private final Map<String, ReductionRuleCondition> rrcMethods = new HashMap<String, ReductionRuleCondition>();
  {
    int i = 0;
    rrcMethods.put("5479284163729206086", new RRC(i++));
    rrcMethods.put("5699937626440454477", new RRC(i++));
    rrcMethods.put("3074048208533316591", new RRC(i++));
    rrcMethods.put("8423551269875501809", new RRC(i++));
    rrcMethods.put("3074048208533352049", new RRC(i++));
    rrcMethods.put("8423551269875491676", new RRC(i++));
    rrcMethods.put("3074048208533391299", new RRC(i++));
    rrcMethods.put("5835056846091763577", new RRC(i++));
    rrcMethods.put("3074048208533428556", new RRC(i++));
    rrcMethods.put("5835056846093536187", new RRC(i++));
    rrcMethods.put("3649993375854808819", new RRC(i++));
    rrcMethods.put("5359602830840575008", new RRC(i++));
    rrcMethods.put("5359602830849679912", new RRC(i++));
    rrcMethods.put("1872263145769797608", new RRC(i++));
    rrcMethods.put("5835056846085886068", new RRC(i++));
    rrcMethods.put("5835056846091822370", new RRC(i++));
  }
  @Override
  @NotNull
  public ReductionRuleCondition getReductionRuleCondition(@NotNull QueryKey identity) {
    ReductionRuleCondition query = identity.forTemplateNode(rrcMethods);
    return (query != null ? query : super.getReductionRuleCondition(identity));
  }
  private static class RRC implements ReductionRuleCondition {
    private final int methodKey;
    public RRC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(ReductionRuleQueryContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.rule_Condition_0_0(ctx);
        case 1:
          return QueriesGenerated.rule_Condition_0_1(ctx);
        case 2:
          return QueriesGenerated.rule_Condition_0_2(ctx);
        case 3:
          return QueriesGenerated.rule_Condition_0_3(ctx);
        case 4:
          return QueriesGenerated.rule_Condition_0_4(ctx);
        case 5:
          return QueriesGenerated.rule_Condition_0_5(ctx);
        case 6:
          return QueriesGenerated.rule_Condition_0_6(ctx);
        case 7:
          return QueriesGenerated.rule_Condition_0_7(ctx);
        case 8:
          return QueriesGenerated.rule_Condition_0_8(ctx);
        case 9:
          return QueriesGenerated.rule_Condition_0_9(ctx);
        case 10:
          return QueriesGenerated.rule_Condition_0_10(ctx);
        case 11:
          return QueriesGenerated.rule_Condition_0_11(ctx);
        case 12:
          return QueriesGenerated.rule_Condition_0_12(ctx);
        case 13:
          return QueriesGenerated.rule_Condition_0_13(ctx);
        case 14:
          return QueriesGenerated.rule_Condition_0_14(ctx);
        case 15:
          return QueriesGenerated.rule_Condition_0_15(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for rule %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("8423551269874544764", new SNQ(i++));
    snqMethods.put("5359602830840869672", new SNQ(i++));
    snqMethods.put("5359602830842050567", new SNQ(i++));
    snqMethods.put("5359602830842052067", new SNQ(i++));
    snqMethods.put("5359602830842079208", new SNQ(i++));
    snqMethods.put("5359602830842080260", new SNQ(i++));
    snqMethods.put("5359602830846083333", new SNQ(i++));
    snqMethods.put("5359602830846083342", new SNQ(i++));
    snqMethods.put("5359602830851824230", new SNQ(i++));
    snqMethods.put("5359602830851824610", new SNQ(i++));
    snqMethods.put("5835056846085919088", new SNQ(i++));
    snqMethods.put("5835056846085924409", new SNQ(i++));
    snqMethods.put("1894891750411800118", new SNQ(i++));
    snqMethods.put("1894891750409616902", new SNQ(i++));
    snqMethods.put("5835056846091788252", new SNQ(i++));
    snqMethods.put("5835056846091789074", new SNQ(i++));
    snqMethods.put("5835056846091808420", new SNQ(i++));
    snqMethods.put("5835056846091834218", new SNQ(i++));
    snqMethods.put("5835056846091834228", new SNQ(i++));
    snqMethods.put("5835056846093559697", new SNQ(i++));
    snqMethods.put("4078973700449554813", new SNQ(i++));
    snqMethods.put("4078973700449554822", new SNQ(i++));
    snqMethods.put("4078973700449562979", new SNQ(i++));
    snqMethods.put("4078973700449562988", new SNQ(i++));
    snqMethods.put("4078973700449574001", new SNQ(i++));
    snqMethods.put("4078973700449574010", new SNQ(i++));
    snqMethods.put("5434035776219666973", new SNQ(i++));
    snqMethods.put("3649993375851707890", new SNQ(i++));
    snqMethods.put("3649993375851677626", new SNQ(i++));
    snqMethods.put("3649993375851677635", new SNQ(i++));
    snqMethods.put("3649993375852800576", new SNQ(i++));
    snqMethods.put("3074048208532581660", new SNQ(i++));
    snqMethods.put("3074048208533384916", new SNQ(i++));
    snqMethods.put("3074048208533426324", new SNQ(i++));
    snqMethods.put("3074048208533426334", new SNQ(i++));
    snqMethods.put("3074048208533462534", new SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    SourceNodeQuery query = identity.forFunctionNode(snqMethods);
    return (query != null ? query : super.getSourceNodeQuery(identity));
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_6_0(ctx);
        case 1:
          return QueriesGenerated.sourceNodeQuery_11_0(ctx);
        case 2:
          return QueriesGenerated.sourceNodeQuery_13_0(ctx);
        case 3:
          return QueriesGenerated.sourceNodeQuery_13_1(ctx);
        case 4:
          return QueriesGenerated.sourceNodeQuery_15_0(ctx);
        case 5:
          return QueriesGenerated.sourceNodeQuery_15_1(ctx);
        case 6:
          return QueriesGenerated.sourceNodeQuery_17_0(ctx);
        case 7:
          return QueriesGenerated.sourceNodeQuery_17_1(ctx);
        case 8:
          return QueriesGenerated.sourceNodeQuery_20_0(ctx);
        case 9:
          return QueriesGenerated.sourceNodeQuery_20_1(ctx);
        case 10:
          return QueriesGenerated.sourceNodeQuery_25_0(ctx);
        case 11:
          return QueriesGenerated.sourceNodeQuery_25_1(ctx);
        case 12:
          return QueriesGenerated.sourceNodeQuery_26_0(ctx);
        case 13:
          return QueriesGenerated.sourceNodeQuery_27_0(ctx);
        case 14:
          return QueriesGenerated.sourceNodeQuery_28_0(ctx);
        case 15:
          return QueriesGenerated.sourceNodeQuery_28_1(ctx);
        case 16:
          return QueriesGenerated.sourceNodeQuery_29_0(ctx);
        case 17:
          return QueriesGenerated.sourceNodeQuery_30_0(ctx);
        case 18:
          return QueriesGenerated.sourceNodeQuery_30_1(ctx);
        case 19:
          return QueriesGenerated.sourceNodeQuery_32_0(ctx);
        case 20:
          return QueriesGenerated.sourceNodeQuery_34_0(ctx);
        case 21:
          return QueriesGenerated.sourceNodeQuery_34_1(ctx);
        case 22:
          return QueriesGenerated.sourceNodeQuery_35_0(ctx);
        case 23:
          return QueriesGenerated.sourceNodeQuery_35_1(ctx);
        case 24:
          return QueriesGenerated.sourceNodeQuery_36_0(ctx);
        case 25:
          return QueriesGenerated.sourceNodeQuery_36_1(ctx);
        case 26:
          return QueriesGenerated.sourceNodeQuery_37_0(ctx);
        case 27:
          return QueriesGenerated.sourceNodeQuery_38_0(ctx);
        case 28:
          return QueriesGenerated.sourceNodeQuery_39_0(ctx);
        case 29:
          return QueriesGenerated.sourceNodeQuery_39_1(ctx);
        case 30:
          return QueriesGenerated.sourceNodeQuery_41_0(ctx);
        case 31:
          return QueriesGenerated.sourceNodeQuery_42_0(ctx);
        case 32:
          return QueriesGenerated.sourceNodeQuery_45_0(ctx);
        case 33:
          return QueriesGenerated.sourceNodeQuery_46_0(ctx);
        case 34:
          return QueriesGenerated.sourceNodeQuery_46_1(ctx);
        case 35:
          return QueriesGenerated.sourceNodeQuery_47_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("6192761117582501231", new SNsQ(i++));
    snsqMethods.put("4078973700447334766", new SNsQ(i++));
    snsqMethods.put("1872263145773680477", new SNsQ(i++));
    snsqMethods.put("2443441604120561833", new SNsQ(i++));
    snsqMethods.put("2443441604120985865", new SNsQ(i++));
    snsqMethods.put("2443441604126997679", new SNsQ(i++));
    snsqMethods.put("5835056846087183810", new SNsQ(i++));
    snsqMethods.put("5359602830849382381", new SNsQ(i++));
    snsqMethods.put("4078973700447324198", new SNsQ(i++));
    snsqMethods.put("5359602830849075077", new SNsQ(i++));
    snsqMethods.put("3649993375852446100", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_3(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_4(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_5(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_0(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_1(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8_0(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8_1(ctx));
        case 10:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_38_0(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("3028449267042619148", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "ContractName"));
    pvqMethods.put("4078973700446331749", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "public/payable"));
    pvqMethods.put("2443441604127015502", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("2443441604127016723", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("2443441604127016957", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("2443441604127017611", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("7074436853573251094", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Contract"));
    pvqMethods.put("5479284163729204204", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("4078973700448325216", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "simikolon"));
    pvqMethods.put("5479284163729205003", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("4078973700448923242", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "simikolon"));
    pvqMethods.put("5479284163729206971", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5699937626440999307", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5479284163730360803", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("2443441604125264814", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Party"));
    pvqMethods.put("5699937626440171796", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("3649993375853459623", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "simikolon"));
    pvqMethods.put("5699937626444158370", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5699937626444158385", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("6625966364251112013", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "!"));
    pvqMethods.put("8423551269874067808", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "trigger"));
    pvqMethods.put("8423551269874071710", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "trigger"));
    pvqMethods.put("6625966364251144684", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), " did not occur"));
    pvqMethods.put("8423551269874295828", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "trigger"));
    pvqMethods.put("6625966364251130005", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), " == "));
    pvqMethods.put("8423551269874301280", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "participant"));
    pvqMethods.put("8423551269874307857", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "participant"));
    pvqMethods.put("6625966364251154694", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), " did not "));
    pvqMethods.put("7240680332691499449", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "trigger"));
    pvqMethods.put("8423551269876681075", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "trigger"));
    pvqMethods.put("6625966364251165144", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "early"));
    pvqMethods.put("8423551269875502560", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("8423551269875502574", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Party"));
    pvqMethods.put("3649993375854125666", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), ";"));
    pvqMethods.put("5359602830840578593", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operand"));
    pvqMethods.put("5359602830840583360", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "operation"));
    pvqMethods.put("3238726216153387342", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "value"));
    pvqMethods.put("5359602830842083611", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "String"));
    pvqMethods.put("5359602830848064958", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5359602830849684537", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5359602830852123435", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "name"));
    pvqMethods.put("5835056846085883344", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("4078973700448623255", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "simikolon"));
    pvqMethods.put("5835056846087810855", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "party"));
    pvqMethods.put("5835056846091788224", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5835056846091788238", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Party"));
    pvqMethods.put("5835056846091844779", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "dateTime"));
    pvqMethods.put("5835056846093559659", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("5835056846093559673", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Party"));
    pvqMethods.put("6625966364252326985", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "After("));
    pvqMethods.put("6625966364252299595", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "dateTime "));
    pvqMethods.put("3649993375852113915", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("3649993375852792485", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "After"));
    pvqMethods.put("3649993375852803726", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "early/late"));
    pvqMethods.put("3074048208532546018", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "integer"));
    pvqMethods.put("3074048208532578411", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("3074048208533342975", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("3074048208533384888", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("3074048208533426296", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
    pvqMethods.put("3074048208533462506", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Name"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_1_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_1_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_2_1(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_3_0(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_3_1(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_4_1(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_6_1(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_7_1(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_8_0(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_8_1(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_9_0(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_9_1(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_9_2(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_9_3(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_9_4(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_9_5(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_9_6(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_9_7(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_9_8(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_9_9(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_9_10(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_9_11(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_10_0(ctx);
        case 32:
          return QueriesGenerated.propertyMacro_GetValue_10_1(ctx);
        case 33:
          return QueriesGenerated.propertyMacro_GetValue_11_0(ctx);
        case 34:
          return QueriesGenerated.propertyMacro_GetValue_12_0(ctx);
        case 35:
          return QueriesGenerated.propertyMacro_GetValue_12_1(ctx);
        case 36:
          return QueriesGenerated.propertyMacro_GetValue_14_0(ctx);
        case 37:
          return QueriesGenerated.propertyMacro_GetValue_16_0(ctx);
        case 38:
          return QueriesGenerated.propertyMacro_GetValue_18_0(ctx);
        case 39:
          return QueriesGenerated.propertyMacro_GetValue_19_0(ctx);
        case 40:
          return QueriesGenerated.propertyMacro_GetValue_23_0(ctx);
        case 41:
          return QueriesGenerated.propertyMacro_GetValue_24_0(ctx);
        case 42:
          return QueriesGenerated.propertyMacro_GetValue_24_1(ctx);
        case 43:
          return QueriesGenerated.propertyMacro_GetValue_27_0(ctx);
        case 44:
          return QueriesGenerated.propertyMacro_GetValue_28_0(ctx);
        case 45:
          return QueriesGenerated.propertyMacro_GetValue_28_1(ctx);
        case 46:
          return QueriesGenerated.propertyMacro_GetValue_31_0(ctx);
        case 47:
          return QueriesGenerated.propertyMacro_GetValue_32_0(ctx);
        case 48:
          return QueriesGenerated.propertyMacro_GetValue_32_1(ctx);
        case 49:
          return QueriesGenerated.propertyMacro_GetValue_37_0(ctx);
        case 50:
          return QueriesGenerated.propertyMacro_GetValue_37_1(ctx);
        case 51:
          return QueriesGenerated.propertyMacro_GetValue_40_0(ctx);
        case 52:
          return QueriesGenerated.propertyMacro_GetValue_41_0(ctx);
        case 53:
          return QueriesGenerated.propertyMacro_GetValue_41_1(ctx);
        case 54:
          return QueriesGenerated.propertyMacro_GetValue_42_0(ctx);
        case 55:
          return QueriesGenerated.propertyMacro_GetValue_43_0(ctx);
        case 56:
          return QueriesGenerated.propertyMacro_GetValue_44_0(ctx);
        case 57:
          return QueriesGenerated.propertyMacro_GetValue_45_0(ctx);
        case 58:
          return QueriesGenerated.propertyMacro_GetValue_46_0(ctx);
        case 59:
          return QueriesGenerated.propertyMacro_GetValue_47_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink elements$9Xin = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff1ff5fdL, 0x49702a64e18759c0L, "elements");
    /*package*/ static final SReferenceLink participant$OmiB = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad503a77L, 0x6e2c7874ad503a78L, "participant");
    /*package*/ static final SContainmentLink triggerStatement$3Fig = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad503a77L, 0x2e4aefaabc0a0d4L, "triggerStatement");
    /*package*/ static final SContainmentLink condition$BBuq = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad503a77L, 0x3c12506715652a2fL, "condition");
    /*package*/ static final SContainmentLink operation$gs9E = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation");
    /*package*/ static final SReferenceLink participant$JU2H = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2dbbedc3a2b95c56L, 0x2dbbedc3a2b95d18L, "participant");
    /*package*/ static final SContainmentLink actions$zhyC = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L, 0x4b6992bf6a89c52dL, "actions");
    /*package*/ static final SContainmentLink actions$m9nt = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad503a77L, 0x3a27346aff20a72bL, "actions");
    /*package*/ static final SReferenceLink timeSpecification$IPtB = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35ec350cL, 0x15208bca35ec350dL, "timeSpecification");
    /*package*/ static final SContainmentLink triggerRef$IUBX = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35ec350cL, 0x15208bca35ec350eL, "triggerRef");
    /*package*/ static final SReferenceLink participant$rnBV = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x15208bca35ec350cL, 0x15208bca35f3858aL, "participant");
    /*package*/ static final SContainmentLink expression$5L7M = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression");
    /*package*/ static final SContainmentLink operand$w6IR = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand");
    /*package*/ static final SReferenceLink Integer$yKP$ = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715400b6eL, 0x3c12506715400bcfL, "Integer");
    /*package*/ static final SReferenceLink dateTime$y$gL = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067151fd807L, 0x3c125067151fd880L, "dateTime");
    /*package*/ static final SReferenceLink participant$k7lb = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x74e67740044e6ed4L, 0x74e67740044e91deL, "participant");
    /*package*/ static final SContainmentLink DateTimeArgument$60K2 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c1250671537c673L, 0x6ab6d4769f14e56bL, "DateTimeArgument");
    /*package*/ static final SReferenceLink timeSpecification$ruqc = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067155b545aL, 0x3c125067155b55f7L, "timeSpecification");
    /*package*/ static final SReferenceLink DateTime$gLMA = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067155b545aL, 0x3c125067155b54bdL, "DateTime");
    /*package*/ static final SReferenceLink duration$PA4 = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e19967b5L, 0x49702a64e1996816L, "duration");
    /*package*/ static final SReferenceLink timeSpecification$oYYj = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c1250671561d371L, 0x3c1250671561d402L, "timeSpecification");
    /*package*/ static final SContainmentLink leftExpression$sEj = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11cL, "leftExpression");
    /*package*/ static final SContainmentLink rightExpression$nvX = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11bL, "rightExpression");
    /*package*/ static final SContainmentLink bool$pu0 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x7678ff525f597e98L, 0x7678ff525f597ec9L, "bool");
    /*package*/ static final SContainmentLink string$pW2 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x7678ff525f597e98L, 0x7678ff525f597ecbL, "string");
    /*package*/ static final SContainmentLink lValue$splI = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue");
    /*package*/ static final SContainmentLink rValue$spNK = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue");
    /*package*/ static final SContainmentLink durationArgument$EbIs = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067153a67eaL, 0x1a4c0201e712ad81L, "durationArgument");
    /*package*/ static final SContainmentLink integerArgument$9WO6 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x74e67740044e6ed4L, 0x1a4c0201e6fb71bfL, "integerArgument");
    /*package*/ static final SContainmentLink Expression$iyr6 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c12506715652a4dL, 0x3c12506715652ac6L, "Expression");
    /*package*/ static final SContainmentLink durationArgument$1A$c = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067155b545aL, 0x4b6992bf6a563d9fL, "durationArgument");
    /*package*/ static final SContainmentLink condition$5R17 = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, 0xf8cc56b218L, "condition");
    /*package*/ static final SContainmentLink DateTimeArgument$p4nE = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c1250671561d371L, 0x3c1250671561d404L, "DateTimeArgument");
    /*package*/ static final SReferenceLink type$xler = MetaAdapterFactory.getReferenceLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2cf24455866a62cdL, 0x2cf24455866a76bdL, "type");
    /*package*/ static final SContainmentLink participants$za28 = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L, 0x4b6992bf6a89c522L, "participants");
    /*package*/ static final SContainmentLink variables$zfTx = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L, 0x4b6992bf6a89c526L, "variables");
    /*package*/ static final SContainmentLink body$e68K = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body");
    /*package*/ static final SContainmentLink statement$53DE = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement");
    /*package*/ static final SContainmentLink clauses$zgA$ = MetaAdapterFactory.getContainmentLink(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad4f9743L, 0x4b6992bf6a89c529L, "clauses");
    /*package*/ static final SContainmentLink ifTrue$5Rg8 = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, 0xf8cc56b219L, "ifTrue");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TokenTransaction$QQ = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18b8ea4L, "SimpleContractLanguage.structure.TokenTransaction");
    /*package*/ static final SConcept Participant_Method_deposit$uS = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x55e1bccfa9c2aceaL, "SimpleContractLanguage.structure.Participant_Method_deposit");
    /*package*/ static final SConcept addDuration$Vc = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c125067153a67eaL, "SimpleContractLanguage.structure.addDuration");
    /*package*/ static final SConcept DateTime_Method_isAfter$2K = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3c1250671537c673L, "SimpleContractLanguage.structure.DateTime_Method_isAfter");
    /*package*/ static final SConcept Action$kj = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x3a27346aff1ff5fdL, "SimpleContractLanguage.structure.Action");
    /*package*/ static final SInterfaceConcept IElements$C3 = MetaAdapterFactory.getInterfaceConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x49702a64e18758e3L, "SimpleContractLanguage.structure.IElements");
    /*package*/ static final SConcept Clause$Sq = MetaAdapterFactory.getConcept(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x6e2c7874ad503a77L, "SimpleContractLanguage.structure.Clause");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty value$jgCM = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value");
    /*package*/ static final SProperty value$w7MM = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value");
    /*package*/ static final SProperty integer$xlGt = MetaAdapterFactory.getProperty(0x73e7dd6392b341e4L, 0xb2c2e5cfe1f50f1fL, 0x2cf24455866a62cdL, 0x2cf24455866a76bfL, "integer");
  }
}
